# -*- coding: utf-8 -*-
"""api_data_gathering (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2Va90fzuRce0Cstcm_fNIudoTqk0jGg
"""

# importing the libraries
import pandas as pd
import requests
import time

# api key
api_key = "50894786170734923bca3c91d9bf29ee"

# define the end_point
end_point = "popular"
url = f"https://api.themoviedb.org/3/movie/{end_point}?api_key={api_key}"

# Send request
response = requests.get(url)
print(response)  # Success, everything worked correct if we get response 200

response.json()

h = response.json()["results"]

df = pd.DataFrame(h)
print(df)

df.head(2)

df.shape

dm = pd.DataFrame()
print(dm)

for i in range(1, 200):
    # Construct the URL with the current page number
    page_url = f"{url}&page={i}"
    try:
        response = requests.get(page_url)
        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            data = response.json()
            # Extract results for the current page
            h_current_page = data["results"]
            # Create a DataFrame for the current page's results
            df_current_page = pd.DataFrame(h_current_page)
            # Append the current page's DataFrame to the main DataFrame 'dm'
            dm = pd.concat([dm, df_current_page], ignore_index=True)
        else:
            print(f"Error fetching page {i}: {response.status_code}")
            break  # Stop if there's an error
    except requests.exceptions.ConnectionError as e:
        print(f"Connection error on page {i}: {e}. Retrying after 5 seconds...")
        time.sleep(5)  # Wait for 5 seconds before retrying
        continue  # Continue to the next iteration
    time.sleep(0.1)  # Small delay to avoid overwhelming the API server

dm.head()

dm.shape

dm.head(2)

dm.to_csv("movies_data.csv")
